# Generated by Django 4.1.2 on 2022-10-25 21:55

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music_project', '0002_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.FloatField(validators=[django.db.models.fields.PositiveIntegerField]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.db.models.fields.PositiveIntegerField]),
        ),
    ]
